"""implementacion de recurrencia simple

Revision ID: 4293300033df
Revises: 79c2c45e56fa
Create Date: 2025-07-16 09:20:52.977115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4293300033df'
down_revision = '79c2c45e56fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recurring', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('days_of_week', sa.String(length=14), nullable=True))
        batch_op.add_column(sa.Column('start_recur', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('end_recur', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('end_recur')
        batch_op.drop_column('start_recur')
        batch_op.drop_column('days_of_week')
        batch_op.drop_column('recurring')

    # ### end Alembic commands ###
