"""Eliminación del metodo recurrente

Revision ID: 82fa1fdfc464
Revises: d4ff8aa1e71a
Create Date: 2025-07-15 08:23:16.554423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82fa1fdfc464'
down_revision = 'd4ff8aa1e71a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('recurrence')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recurrence', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
