"""empty message

Revision ID: d4ff8aa1e71a
Revises: 027085ea7343
Create Date: 2025-07-14 21:38:19.062804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4ff8aa1e71a'
down_revision = '027085ea7343'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recurrence', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('recurrence')

    # ### end Alembic commands ###
