"""Integración de manejo de fechas flexible

Revision ID: fb58e9780911
Revises: 82fa1fdfc464
Create Date: 2025-07-15 08:49:33.789631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb58e9780911'
down_revision = '82fa1fdfc464'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('start_date',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('end_date',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('end_date',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('start_date',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
